# Don't post a comment on pull requests.
comment: off

# Sets non-blocking status checks
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
    changes: no
