name: ci
on: push
jobs:
  test-27:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
    env:
      NOSE_SHOW_SKIPPED: 1
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox sphinx
      - name: Test with tox
        run: |
          tox -e py27-test
          tox -e docs
  test-3x:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        python-version: [ 5, 6, 7, 8 ]
    env:
      NOSE_SHOW_SKIPPED: 1
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.${{ matrix.python-version }}
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox sphinx
      - name: Test with tox
        run: |
          if [[ ${{ matrix.python-version }} == '8' ]]; then
              tox -e py3${{ matrix.python-version }}-test
              tox -e py3${{ matrix.python-version }}-cov
              tox -e py3${{ matrix.python-version }}-flake8
          else
              tox -e py3${{ matrix.python-version }}-test
          fi
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python to build docs with sphinx
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox sphinx
      - name: Build and check docs using tox
        run: tox -e docs