name: formatting_check
run-name: Check code formatting
on: [push, pull_request]
jobs:
  formatting_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Run formatting check
        run: poetry run project check-format
