name: integration tests
on:
  schedule:
    - cron: '0 0 * * SUN'  # run every Sunday at midnight
jobs:
  test integration:
    runs-on: ubuntu-latest
    strategy:
      python-version: 3.8
    env:
      NOSE_SHOW_SKIPPED: 1
      PY_COLOR: 1
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test with tox
        run: |
          tox -e int